version: 0.2

env:
  variables:
    REPO_NAME: xxxx
    AWS_DEFAULT_REGION: ap-southeast-1

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - AWS_ECR_ACCOUNT_URL=$(aws sts get-caller-identity --query Account --output text).dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - VERSION=$(jq -r '.version' package.json)
      - REPOSITORY_URI=$AWS_ECR_ACCOUNT_URL/$REPO_NAME-$ENV

  build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ECR_ACCOUNT_URL
      - docker build -t $REPOSITORY_URI:latest --build-arg ENV_NAME=$ENV .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$VERSION

  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$VERSION
